#!/usr/bin/with-contenv bash
mkdir -p /config/log

if [ ! -e /config/netdata.conf ]; then
  cp /default/netdata.conf /config
  cp -r /etc/netdata/* /config
fi

# permissions
chown -R abc:abc \
	/config \
  /usr/share/webapss/netdata \
  /var/lib/netdata \
  /var/cache/netdata
